stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    # params:
    # - 
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    # params:
    # - 
    outs:
    - data/interium
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/interium
    - src/feature_engineering.py
    # params:
    # - 
    outs:
    - data/processed
  model_training:
    cmd: python src/model_training.py
    deps:
    - data/processed
    - src/model_training.py
    # params:
    # - 
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json